name: فك ضغط ملف ZIP

on:
  push:
    paths:
      - '*.zip'
  workflow_dispatch:

jobs:
  unzip:
    runs-on: ubuntu-latest
    steps:
      - name: جلب الكود
        uses: actions/checkout@v4

      - name: فك الضغط
        run: |
          sudo apt-get install unzip
          unzip -o '*.zip' -d ./
          rm -f *.zip

      - name: دفع التغييرات
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "فك ضغط الملفات وحذف ZIP" || echo "لا تغييرات"
          git push
